<?php
/**
 * @version   1.5.1.1 September 1, 2011
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2011 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 * Overrides template/callouts/right_col.phtml - Adds ability to specify content from admin panel
 */
?>

<?php
// Check if Left CmsCallout  is ON or OFF
    $configData = Mage::getStoreConfig('cms_callouts');
	$rightpower = $configData['general']['enableright'];
// Get Callout Title
    $configData = Mage::getStoreConfig('cms_callouts');
	$righttitle = $configData['settings']['rightcallouttitle'];
// Get Callout Text
    $configData = Mage::getStoreConfig('cms_callouts');
	$rightcontent = $configData['settings']['rightcallouttext'];
// Get CMS Block
	$configData = Mage::getStoreConfig('cms_callouts');
	$rightcalloutblock = $configData['settings']['rightcalloutblock'];
?>

<?php if($rightpower == 1) : ?>
<div class="block callout">
    <div class="block-title">
        <strong><span><?php echo $righttitle ?></span></strong>
    </div>
    <div class="block-content">
	<?php echo $rightcontent ?>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($rightcalloutblock)->toHtml(); ?>
    </div>
</div>
<?php endif; ?>