<?php
/**
 * @version   1.7.0.0 May 15, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 * Specific to Moxy
 */
?>

<script type="text/javascript">
     var $j = jQuery.noConflict();
$j('document').ready(function(){
fontSize(".fontResizer", ".wrapper", 11, 13, 15, "<?php echo $this->__('Text Size') ?>", "MoxyCookie", "A", "A");
});
</script>

<div class="fontResizer"></div>