<?php
/**
 * @version   1.7.0.2 May 11, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
?>
	
<?php $currurl = Mage::helper('adminhtml')->getUrl('*/*/index'); if(stristr($currurl, 'system_config')) : // If we're on the system configuration page '?> 
    <?php // Get the current theme being used, so we can build the url link to our jQuery file
    $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
	$tablename = Mage::getSingleton('core/resource')->getTableName('core_config_data');
	$results = $connection->fetchAll("SELECT * FROM $tablename WHERE path='design/package/name';");
    foreach($results as $row) { $theme = $row['value']; };
    ?>

<?php $jquery = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/'.$theme.'/default/rokmage-main-js/jquery.min.js'; ?>
<?php if (file_exists($jquery)): ?>
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/'.$theme; ?>/default/rokmage-main-js/jquery.min.js"></script>
<?php else: ?>
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/rokmage-main-js/jquery.min.js"></script>
<?php endif; ?>
	
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>tiny_mce/jquery.tinymce.js"></script>
    <?php
    // Get the list of textareas ID's to enable for
    $configData = Mage::getStoreConfig('tiny_mce');
    $textareas = $configData['general']['enabledfor'];
    ?>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function() {

        // Get our url for the script
        address1 = window.location.protocol + "//" + window.location.host + window.location.pathname;
        address2 = address1.split("index.php");
        scripturl = address2[0] + 'js/tiny_mce/tiny_mce.js';

        $j('<?php echo $textareas ?>').tinymce({

            // Location of TinyMCE script
            script_url : scripturl,

            // General options
            theme : "advanced",
            plugins : "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

            // Theme options
            theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmapiespell,advhr,|,print,|,ltr,rtl",
            //	theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true,

            relative_urls : false,//Tiny upload returns absolute urls, we dont want tinymce changing them to relative.
            file_browser_callback:tinyupload//Hookup tinyupload the the filebrowser call back.

        });


        // Add ON OFF toggle switch to each
    <?php $array = explode(', ', $textareas);
    $array = str_replace('#', '', $array); ?>

    <?php foreach ($array as $tinyid):  ?>
        $j('textarea#<?php echo $tinyid; ?>').before("<span class=\"toggle_<?php echo $tinyid; ?> form-button\">Show / Hide Editor</span><br/><br/>"); // Add toggle switch
        $j("span.toggle_<?php echo $tinyid; ?>").toggle(function(){ // Add toggle function
            tinyMCE.execCommand('mceRemoveControl', false, '<?php echo $tinyid; ?>'),
            $j('.form-list td.value .textarea').css("height","16.25em");
        }, function () {
            tinyMCE.execCommand('mceAddControl', false, '<?php echo $tinyid; ?>'),
            $j(".defaultSkin iframe").css("height","100px");
        });
    <?php endforeach; ?>

    });
</script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>rokmage_tinymce/tinyupload.js"></script>
<style type="text/css">
span.form-button {
background-image:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>/adminhtml/default/default/images/btn_show-hide_icon.gif");
background-position:5%  50%;
background-repeat:no-repeat;
padding:3px 10px 3px 30px;
line-height:1.35em;
}
</style>
<?php endif; ?>