<?php
/**
 * @version   1.7.0.0 May 15, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 * Overrides template/page/template/links.phtml - Adds modal header cart and spacer for text-resizer
 */
?>

<?php
	// Get modal animation settings from admin
	$configData = Mage::getStoreConfig('modal_header');
	$animation = $configData['settings_modalanimation']['animation'];
	// Check if text size disabled
	$textsize = $configData['general']['disabletextsize'];
	// Check if modal cart disabled
	$modalcart = $configData['general']['disablemodalcart'];
?>

<?php if($modalcart == 0): ?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('a.modal, .summary .amount a').rokmagemodal({ rokmagemodalcontainer: "#rokmage-header-cart", <?php echo $animation ?> });
    });
</script>
<?php endif; ?>

<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>

<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>

<div class="rokmage-cart-box-container">
    <div class="rokmage-cart-box-R">
        <div class="rokmage-cart-box-L">
                <?php $_cartQty = Mage::getSingleton('checkout/cart')->getSummaryQty(); ?>
                <?php if ($_cartQty==0): ?>
            <img src="<?php echo $this->getSkinUrl('rokmage-modalheader/images/cart-empty-icon.png') ?>" class="cart-icon" alt="" /><span class="big">0</span><span class="items-checkout"><?php echo $this->__('items') ?> <span class="inactive"><?php echo $this->__('in your cart') ?></span></span>
                <?php else: ?>
                    <?php if ($_cartQty==1): ?>
            <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="modal"><img src="<?php echo $this->getSkinUrl('rokmage-modalheader/images/cart-1item-icon.png') ?>" class="cart-icon" alt="" /></a><span class="big"><?php echo $_cartQty ?></span><span class="items-checkout"><?php echo $this->__('item') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="active modal no-wrap"><?php echo $this->__('view cart') ?></a></span>
                    <?php else: ?>
            <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="modal"><img src="<?php echo $this->getSkinUrl('rokmage-modalheader/images/cart-icon.png') ?>" class="cart-icon" alt="" /></a><span class="big"><?php echo $_cartQty ?></span><span class="items-checkout"><?php echo $this->__('items') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="active modal no-wrap"><?php echo $this->__('view cart') ?></a></span>
                    <?php endif; ?>
                <?php endif; ?>
        </div>
    </div>
</div>

<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
        <?php foreach($_links as $_link): ?>
			<?php if ($_link instanceof Mage_Core_Block_Abstract):?>
	            <?php echo $_link->toHtml() ?>
	        <?php else: ?>
    <li<?php if($_link->getIsFirst()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
			<?php endif;?>
        <?php endforeach; ?>
    <?php if ($textsize != 1): ?><li><a href ="#">Text Size Inactive</a></li><?php endif; ?>
</ul>
<?php endif; ?>
