<?php
/**
 * @version   $Id: 2columns-left.phtml 47705 2012-01-18 21:55:02Z sam $
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="mage-iphone'.$this->getBodyClass().'"':'' ?> home="index.php" onload="setTimeout(scrollTo, 0, 0, 1)">
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<div data-role="page">
    <div class="header">
        <?php echo $this->getChildHtml('header') ?>
    </div>

    <div class="middle-container">
        <div class="middle col-1-layout">
            <?php // echo $this->getChildHtml('breadcrumbs') ?>
            <div class="clear"></div>
            <div id="main" class="col-main">
                <div <?php echo $this->getBodyClass()?' class="mage-iphone'.$this->getBodyClass().'"':'' ?>>
                    <?php //if($sliderpowerhome == '1') : ?>
                        <?php echo $this->getChildHtml('rokmage_content_slider') ?>
                    <?php //endif; ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
    </div>

    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
