<?php
/**
 * @version   1.7.0.0 May 5, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
?>

<?php // Get the default product layout
$configData = Mage::getStoreConfig('homepage_grid');
$defaultlayout = $configData['settings']['defaultlayout'];
if($defaultlayout == 'grid') {
    echo '<script type="text/javascript">var $j = jQuery.noConflict(); $j(document).ready(function(){$j("ul.display").addClass("thumb_view");$j("span.switch_thumb").addClass("swap");});</script>';
};
?>

<div>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function(){

        $j(".sorter .view-mode").css("display", "none");
        $j("span.switch_thumb").css("display", "none");

        $j("span.switch_thumb").click(function () {
            $j("span.switch_thumb").toggleClass("swap");
            $j("ul.display").animate({opacity: 0},"fast", function() {
                $j(this).animate({opacity: 1},"fast").toggleClass("thumb_view").toggleClass("list");
                // Undo equalized heights for list
                $j('ul.list div.product-container').css("height","auto");
                // Equalize all thumb heights on switch if list view default
                var maxHeight = 0;
                $j('ul.thumb_view div.product-container').each(function() { 
					maxHeight = Math.max(maxHeight, $j(this).height()) + 1; 
					}).height(maxHeight);
            });
            $j.cookie('view_State', $j('ul.display').is('.thumb_view') ? 'list' : 'thumbs' );
        });

        // COOKIES
        // view state
        var view_State = $j.cookie('view_State');
        // Set the user's selection for the viewState
        if (view_State == 'thumbs') {
            $j("ul.display").addClass("thumb_view");
            $j("span.switch_thumb").addClass("swap");
        };
        if (view_State == 'list') {
            $j("ul.display").removeClass("thumb_view");
            $j("span.switch_thumb").removeClass("swap");
        };
    });

</script>

<?php // HOMEPAGE SETTINGS
// Get the title of the product grid
$configData = Mage::getStoreConfig('homepage_grid');
$gridtitle = $configData['settings']['grid_title'];
// Get the text for the product grid
$gridtext = $configData['settings']['grid_text'];
// Get the number of items to show from admin
$no_of_items = $configData['settings']['no_of_products'];
// Check if Randomize is ON or OFF
$randomize = $configData['settings']['randomize'];
// Check if Truncate is ON or OFF
$truncate = $configData['settings']['truncate'];
// Get Truncate Title Length
$titlelength = $configData['settings']['truncate_titlelength'];
// Get Truncate Description Length
$desclength = $configData['settings']['truncate_desclength'];
// Get the attribute to filter from admin
$filter_by = $configData['settings']['filter_by'];
// If select list being used
if ($filter_by == 'selectlist') {
// Get list of selected products from backend
    $featuredlist = $configData['settings']['productlist'];
	$featuredlist = explode(',', $featuredlist); };
// If featured products being used
if ($filter_by == 'featured') {
// Get Featured category type from backend
    $configData = Mage::getStoreConfig('featured_products');
    $featuredtype = $configData['general']['featuredtype'];
    // Get Featured category from backend
    $featuredcategory = $configData['settings']['featuredcategory'];
    // Get Featured attribute from backend
    $featuredattribute = $configData['settings']['featuredattribute'];
    // Get Featured Products from list
    if($featuredtype == 'list') {
        $featuredlist = $configData['settings']['featuredlist'];
		$featuredlist = explode(',', $featuredlist); };
};
// Get List Image Height
$configData = Mage::getStoreConfig('homepage_grid');
$listimageheight = $configData['settings']['listimageheight'];
// Get List Image Width
$listimagewidth = $configData['settings']['listimagewidth'];
// Check if Ribbon is disabled
$ribbon = $configData['settings']['ribbons'];
?>

<?php if($truncate == 'truncate') { $truncatetitle = 'truncate_grid_title' ; $truncatedesc = 'truncate_grid_desc'; } else { $truncatetitle = '' ; $truncatedesc = '';}; ?>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    // Truncate
    $j(function() {
        $j('.truncate_grid_title').truncate({max_length: <?php echo $titlelength ?>});
        $j('.truncate_grid_desc').truncate({max_length: <?php echo $desclength ?>});
    });
    $j(document).ready(function(){
        // Remove list class if thumbview
        if ( $j("ul#products-list").hasClass("thumb_view") ) {
            $j("ul#products-list").removeClass("list") };
        // Equalize all thumb heights on switch if list view default
        var maxHeight = 0;
        $j('ul.thumb_view div.product-container').each(function() { maxHeight = Math.max(maxHeight, $j(this).height()) + 1; }).height(maxHeight);
        // Undo equalized heights for list
        $j('ul.list div.product-container').css("height","auto");
    });
</script>
</div>

<?php
// Check product visibility
$visibility = array(
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);

// Check if root filter is ON
$configData = Mage::getStoreConfig('featured_products');
$filterbyroot = $configData['settings']['filterbyroot'];

// Get the current category
if ($filterbyroot == 1) { // If filter by root is enabled
        $_currcat = Mage::app()->getStore()->getRootCategoryId();
} else {
        $_currcat = 0;
};
$_category = Mage::getModel('catalog/category')->load($_currcat);

// Select attributes
$_attributes = array('name', 'price', 'small_image', 'short_description', 'is_salable', 'msrp_enabled', 'msrp_display_actual_price_type', 'msrp', 'apply_to');

// Get Product Collection Model
$_productCollection = Mage::getResourceModel('featuredproducts/product_collection')->addAttributeToFilter('status', 1);

//** All Products **//
if ($filter_by == 'all') {
    $_productCollection->filterbyFullCollection($_attributes,$visibility,$_category,$no_of_items,$randomize, $_currcat);
    // Get size of collection
    $size = $_productCollection->getSize(); }

//** Best-Selling - load a product collectionfiltered by best-selling **//
elseif($filter_by == 'bestselling') {
    $_productCollection->filterbyBestSelling($_attributes,$visibility,$_category,$no_of_items, $_currcat);
    // Get size of collection
    $size = $_productCollection->getSize(); }

//** Select List **//
if ($filter_by == 'selectlist') {
//** Featured - load a product collection selected in the HomepageGrid admin **//
    $_productCollection->filterbyFullCollection($_attributes,$visibility,$_category,$no_of_items,$randomize, $_currcat)->addAttributeToFilter('entity_id', array('in'=>array($featuredlist)));
    // Get size of collection
    $size = $_productCollection->getSize(); }

//** Featured **//
elseif($filter_by == 'featured') {
    if ($featuredtype == 'list') {
    //** Featured - load a product collection selected in the admin **//
        $_productCollection->filterbyFullCollection($_attributes,$visibility,$_category,'',$randomize, $_currcat)->addAttributeToFilter('entity_id', array('in'=>array($featuredlist)))->setPageSize($no_of_items);
        // Get size of collection
        $size = $_productCollection->getSize(); }
    elseif ($featuredtype == 'attribute') {
    //** Featured - load a product collection filtered by featured attribute **//
        $_productCollection->filterbyFeaturedAttribute($_attributes,$visibility,$featuredattribute,$_category,$no_of_items,$randomize, $_currcat);
        // Get size of collection
        $size = $_productCollection->getSize(); }
    elseif ($featuredtype == 'category') {
    //** Featured - load a product collection filtered by featured category **//
        $_featcategory = Mage::getModel('catalog/category')->load($featuredcategory); // Load featured category
        $_productCollection->filterbyFeaturedCategory($_attributes,$visibility,$_featcategory,$no_of_items,$randomize, $_currcat);
        // Get size of collection
        $size = $_productCollection->getSize(); }
}

//** Recently Added - load a product collection filtered by recently added **//
elseif($filter_by == 'recent') {
    $_productCollection->filterbyRecentlyAdded($_attributes,$visibility,$_category,$no_of_items, $_currcat);
    // Get size of collection
    $size = $_productCollection->getSize(); }

//** Most Viewed - load a product collection filtered by most views **//
elseif($filter_by == 'viewed') {
    $_productCollection->filterbyMostViewed($_attributes,$visibility,$_category,$no_of_items, $_currcat);
    // Get size of collection
    $size = $_productCollection->getSize(); }

//** Highest Rated - load a product collection filtered by ratings **//
elseif($filter_by == 'rated') {
    $_productCollection->filterbyHighestRated($_attributes,$visibility,$_category,$no_of_items, $_currcat);
    // Get size of collection
    $size = $_productCollection->getSize(); }

//** Special Price - load a collection of products currently with Special Price **//
elseif($filter_by == 'specialprice') {
    $_productCollection->filterbySpecialPrice($_attributes,$visibility,$_category,$no_of_items, $_currcat);
    // Get size of collection
    $size = $_productCollection->getSize(); }
?>

<div class="bg-container">
    <header class="category-title page-title">
        <h1><?php echo $gridtitle; ?></h1>
    
    <div class="grid-text">
        <?php if(stristr($gridtext, 'type="blog/blog"')) { } else { echo $gridtext; }; ?>
    </div>
	</header>
    <?php if($no_of_items == 0) : // If product list disabled ?>

	        <?php if(stristr($gridtext, 'type="blog/blog"')) { // If grid text is set to display AW Blog posts
	            $exploded = explode("template=", $gridtext); $exploded1 = $exploded[1];
	            (preg_match('/"([^"]+)"/', $exploded1, $template)) ;
	            echo $this->getLayout()->createBlock('blog/blog')->setTemplate($template[1])->toHtml() ;} ;
	        ?>

	<?php else: ?>
        <?php // Mixed mode ?>
    <section class="category-products <?php if ($ribbon == '0'): ?><?php echo $filter_by ?><?php endif; ?>">
        <span id="switch_thumb" class="switch_thumb"><?php echo $this->__('Switch View') ?></span>
            <?php $_iterator = 0; ?>
        <ul class="display list" id="products-list">
                    <?php foreach ($_productCollection as $_product):  ?>
					<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); $_is_saleable = $_product->getData('is_salable'); ?>
            <li itemscope itemtype="http://schema.org/Product" class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                <div class="product-container">
                    <div class="product-image-col">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <figure>                                
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($listimagewidth, $listimageheight); ?>" width="<?php echo 213//$listimagewidth ?>" height="<?php echo 220//$listimageheight ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </figure>
                        </a>
                                    <?php if($_is_saleable == 1): ?>
                                        <?php
                                        $qty = 1;
                                        $url = Mage::getUrl('checkout/cart/add', array('product' => $_product->entity_id,'qty' => $qty)) ;
                                        ?>
                        <button class="button" onclick="setLocation('<?php echo $url ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php else: ?>
                        <div class="availability"><span itemprop="availability" class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></div>
                                    <?php endif; ?>
                    </div>
                    <div class="product-info-col">
                        <h2 itemprop="name" class="product-name <?php echo $truncatetitle ?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"><?php echo $_productNameStripped ?></a></h2>
                                    <?php // Check if reviews tab enabled for productview
                                    $configData = Mage::getStoreConfig('product_view');
                                    $reviews = $configData['info_settings']['reviews'];
                                    if ($reviews == 1): ?>
                                        <?php
                                        $storeId = Mage::app()->getStore()->getId();
                                        $summaryData = Mage::getModel('review/review_summary')
                                            ->setStoreId($storeId)
                                            ->load($_product->getId());
                                        if($summaryData->getRatingSummary() != '') { echo '<div class="ratings">
								                                        <div class="rating-box">
								                                        <div class="rating" style="width: '.$summaryData->getRatingSummary().'%"></div>
								                                        </div>
								                                        <p class="rating-links">
								                                            <a href="'.$_product->getProductUrl().'#reviews">'.$summaryData->getReviewsCount().' '.$this->__('Reviews(s)').'</a>
								                                            <span class="separator">|</span>
								                                            <a href="'.$_product->getProductUrl().'#review-form">'.$this->__('Add Your Review').'</a>
								                                        </p></div>';};
                                        ?><?php endif; ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <p class="product-desc <?php echo $truncatedesc ?>"><?php echo $_product->getShortDescription() ?></p>
                        <span class="addto"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"><?php echo $this->__('Learn More') ?></a></span><span class="spacer-hide"> | </span>
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <span class="addto"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></span><span class="spacer-hide"> | </span>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <?php $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ?>
                        <span class="addto"><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></span>
                                    <?php endif; ?>
                    </div>
                    <div class="clearfloat"></div>
                </div><?php if ($ribbon == '0'): ?><span class="ribbon"></span><?php endif; ?>
            </li>
                    <?php endforeach; ?>
        </ul>
    </section>
    <?php endif; ?>
    <div class="clearfloat"></div>
</div>
<div class="bg-container-end"></div>

<?php // Check if reviews enabled in extension
$configData = Mage::getStoreConfig('product_view');
$reviews = $configData['info_settings']['reviews'];
if ($reviews == 1): ?>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function(){
        $j(".product-info-col").each(function(){
            var link = $j("a:eq(0)", this).attr('href');
            $j(".rating-links a:first", this).attr("href", link + "#reviews");
            $j(".rating-links a:last", this).attr("href", link + "#review-form");
        });
    });
</script>
<?php endif; ?>