<?php
/**
 * @version   $Id: rokmage-categoryview.phtml 47705 2012-01-18 21:55:02Z sam $
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 * Overrides template/catalog/product/list.phtml
 */
?>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>

<?php
  // Check if enabling filter
  $configData = Mage::getStoreConfig('rokmage_mobile');
  $listfilter = $configData['catalog_settings']['listfilter'];
  // Check if showing rating stars
  $ratingstars = $configData['catalog_settings']['ratingstars']; 
?>

<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php // Mixed mode ?>
<div class="toolbar-wrapper">
        <?php echo $this->getToolbarHtml() ?>
    </div>
<div class="category-products" data-role="content" data-content-theme="c">
    
        <?php $_iterator = 0; ?>
    <ul data-role="listview" data-theme="c" <?php if($listfilter == 1): ?>data-filter="true" data-filter-placeholder="<?php echo 'Filtrar Listagem de Produtos...' ?>"<?php endif; ?>>
        <?php foreach ($_productCollection as $_product): ?>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li>
            <a class="product-link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">    
                <img class="thumb" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80); ?>" alt="<?php echo $_productNameStripped; ?>" title="<?php echo $_productNameStripped; ?>" />
                <h2 class="product-name <?php echo $truncatetitle ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h2>
                <div class="prices"><?php echo $this->getPriceHtml($_product, true); ?></div>
                <?php if($ratingstars == 1): ?>
                    <?php if($_product->getRatingSummary()): ?>    
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?> 
                <?php endif; ?>       
            </a>   
        </li>
        <?php endforeach; ?>
    </ul>
    
</div>
<div class="toolbar-wrapper bottom"><?php echo $this->getToolbarHtml() ?></div>
<?php endif; ?>
