<?php
/**
 * @version   1.7.0.0 May 5, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
?>

<?php // Get additional jQuery
    $configData = Mage::getStoreConfig('modal_header');
    $jquery = $configData['settings_js_css']['additional_js'];
    if($jquery != '') : // IF EXTRA JQUERY ?>
    <script type="text/javascript">
        <?php echo $jquery; ?>
    </script>
<?php endif;  ?>