<?php
/**
 * @version   1.7.0.0 May 5, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
?>

<?php
	// Get modal animation settings from admin
	$configData = Mage::getStoreConfig('modal_header');
	$animation = $configData['settings_modalanimation']['animation'];
    // Check if modal login disabled
	$configData = Mage::getStoreConfig('modal_header');
	$login = $configData['general']['disablemodallogin'];
	// Check if redirect to dash is off
	$configData = Mage::getStoreConfig('customer');
	$redirectdashboard = $configData['startup']['redirect_dashboard'];
?>

<?php if ($login != 1): // If modal login isn't disabled ?>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready( function() {
        $j('a[title="<?php echo $this->__('Log In') ?>"]').rokmagemodal({ rokmagemodalcontainer: "#rokmage-login-content", <?php echo $animation ?> });
	<?php if($redirectdashboard == 0): ?>
		var reflink = $j('a[title="<?php echo $this->__('Log In') ?>"]', this).attr('href').split("login/");
		var reflink = reflink[1]; var reflink = "<?php echo $this->getPostActionUrl() ?>" + reflink;
		$j("#rokmage-login-content form").attr('action',reflink);
	<?php endif; ?>
    });
</script>

<div id="rokmage-login-content" class="modalcontent">
            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form2">
                <fieldset>
                    <legend>Log In</legend>
                    <h2><?php echo $this->__('Log In') ?></h2>
                    <div class="rokmage-email-login-block">
                        <label for="email"><?php echo $this->__('Email Address') ?></label>
                        <input name="login[username]" value="<?php echo $this->stripTags($this->getUsername(), null, true) ?>" id="email" type="text" class="input-text required-entry" title="<?php echo $this->__('Email Address') ?>" />
                    </div>

                    <div class="rokmage-password-login-block">
                        <label for="pass"><?php echo $this->__('Password') ?></label>
                        <input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                    </div>
                    <div class="clearfloat"></div>

                    <button class="button" type="submit" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    <p class="rokmage-forgot-pass"> <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a></p>
                    <div class="clearfloat"></div>
                </fieldset>
            </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form2', true);
        //]]>
    </script>
</div>
<?php endif; ?>