<?php
/**
 * @version   $Id: mobilecheck.phtml 53433 2012-06-04 20:40:13Z sam $
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 * Overrides template/page/html/footer.phtml - Adds footer logo and "Back to top" link
 */
?>

<?php
 
function detectMobileDevice() {
    $mobile_ua = strtolower(substr($_SERVER['HTTP_USER_AGENT'], 0, 4));
    $mobile_agents = array(
        'w3c ','acs-','alav','alca','amoi','audi','avan','benq','bird','blac',
        'blaz','brew','cell','cldc','cmd-','dang','doco','eric','hipt','inno',
        'ipaq','java','jigs','kddi','keji','leno','lg-c','lg-d','lg-g','lge-',
        'maui','maxo','midp','mits','mmef','mobi','mot-','moto','mwbp','nec-',
        'newt','noki','oper','palm','pana','pant','phil','play','port','prox',
        'qwap','sage','sams','sany','sch-','sec-','send','seri','sgh-','shar',
        'sie-','siem','smal','smar','sony','sph-','symb','t-mo','teli','tim-',
        'tosh','tsm-','upg1','upsi','vk-v','voda','wap-','wapa','wapi','wapp',
        'wapr','webc','winw','winw','xda ','xda-');
    if (preg_match('/(up.browser|up.link|mmp|symbian|smartphone|midp|wap|phone|android)/i', strtolower($_SERVER['HTTP_USER_AGENT']))) {
        return true;
    }
    else if ((strpos(strtolower($_SERVER['HTTP_ACCEPT']),'application/vnd.wap.xhtml+xml') > 0) or ((isset($_SERVER['HTTP_X_WAP_PROFILE']) or isset($_SERVER['HTTP_PROFILE'])))) {
        return true;
    }   
    else if (in_array($mobile_ua,$mobile_agents)) {
        return true;
    }
    else if (strpos(strtolower($_SERVER['HTTP_USER_AGENT']),'OperaMini') > 0) {
        return true;
    }
    else if (strpos(strtolower($_SERVER['HTTP_USER_AGENT']),'windows') > 0) {
        return true;
    }
    else {
        return false;
    }
}
 
if(detectMobileDevice()){
   echo '<div class="viewmobile"><a class="switchtodesktop" href="'.$this->getUrl('switchtheme/index/toMobile').'">'.$this->__('View Mobile Version').'</a></div>';
};
 
?>